### ISSUE TITLE
[Suggestion] Add option to mention a person/role in messages

### ISSUE THREAD

**Issue by notlet** [DenisD3D/Mc2Discord#113]
When the bot sends a message, it automatically disables all mentions. It would be nice if there was a variable to add a mention that actually mentions people, for example when the server starts up the bot automatically pings a role so people know when it's up.

![image](https://github.com/DenisD3D/Mc2Discord/assets/48136206/c2123981-1fdc-4811-8d5d-c1a6d64a6fbb)

Also, whenever people get mentioned in the bridge channel, the mention also works in the log channel, which results in a double ping for people with access to both.

![image](https://github.com/DenisD3D/Mc2Discord/assets/48136206/85e60f2e-427b-4ded-83db-23e20a3037bc)

**Comment by DenisD3D** [comment]
You can configure the allowed mention in the configuration file : 
```toml
[Misc]
# List of allowed mentions from minecraft (supported value: "EVERYONE_AND_HERE", "ROLE", "USER")
allowed_mention = ["ROLE", "USER"]
```
Are thoses configuration enough for your use case ?
Also you might be able to supress ping for a specific channel in your Discord client setting. I will try to disable ping for logs message in the next version
