### ISSUE TITLE
Cannot separate the commands log from the main chat

### ISSUE THREAD

**Issue by silasclockwork** [DenisD3D/Mc2Discord#131]
### Describe the bug

I am struggling to find the way to send all of the normal MC chat logs to my ingame chat channel, and send just the command logs to a admin view only command log channel. 

If I missed something, I'd love to know. If this isn't an unintentional bug, this is me giving you a feature request.

Thanks!

**Comment by DenisD3D** [comment]
Hello,
Is something like this configuration doing what you want ? If not could you details the behavior you want different?
```toml
[Channels]
    [[Channels.Channel]]
        id = 123456789123456789 #channel for chat messages
        subscriptions = ["info", "chat", "command"]
        mode = "WEBHOOK"

    [[Channels.Channel]]
        id = 987654321987654321 # channel for console logs
        subscriptions = ["logs", "command"]
        mode = "WEBHOOK"
```
