### ISSUE TITLE
Feature Request: Announcements channel

### ISSUE THREAD

**Issue by Anti-Apple4life** [DenisD3D/Mc2Discord#132]
I have a server where we have one channel that is synced with the game chat, and another channel for announcements. Is there a way to set up a channel for only discord to minecraft, preferably with a different chat format?

**Comment by DenisD3D** [comment]
Hello,
You can use the "discord" subscription type in your channel settings in mc2discord.toml. This subscription only relay message from Discord to Mc, not the other way arround. Howevern you will not be able to set a different message format for it :(

**Comment by Anti-Apple4life** [comment]
I am having trouble understanding exactly what to do. Can you please send a config snippet?

**Comment by DenisD3D** [comment]
Something like this
```toml
[Channels]

	[[Channels.Channel]]
		# Id of the Discord channel to send messages in (see: https://github.com/DenisD3D/Mc2Discord/wiki/Discord-ids)
		id = CHANNEL_ID_GOES_HERE
		# List of messages types to send that will be sent in this channel. Available values: "info", "chat", "command", "logs"  ("info" is equivalent adding "server_start", "server_stop", "player_connect", "player_disconnect", "player_death", "player_advancement")
		subscriptions = ["discord"]
		# Messages format in this channel. Available values: WEBHOOK, PLAIN_TEXT, EMBED
		mode = "WEBHOOK"
```
